apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wpapp
  name: wpapp
  namespace: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wpapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wpapp
    spec:
      containers:
      - image: wordpress
        name: wordpress
        resources: {}
status: {}
