apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wpapp
  name: wpapp
  namespace: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wpapp
  type: LoadBalancer
status:
  loadBalancer: {}
